version: "3.8"

services:
  app_blue:
    image: ${BLUE_IMAGE}
    environment:
      - APP_POOL=blue
      - RELEASE_ID=${RELEASE_ID_BLUE}
      - PORT=${PORT}
    ports:
      - "${BLUE_HOST_PORT}:${PORT}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/healthz"]
      interval: 5s
      timeout: 3s
      retries: 3
    restart: unless-stopped
    labels:
      - "com.cool-keeds.pool=blue"

  app_green:
    image: ${GREEN_IMAGE}
    environment:
      - APP_POOL=green
      - RELEASE_ID=${RELEASE_ID_GREEN}
      - PORT=${PORT}
    ports:
      - "${GREEN_HOST_PORT}:${PORT}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/healthz"]
      interval: 5s
      timeout: 3s
      retries: 3
    restart: unless-stopped
    labels:
      - "com.cool-keeds.pool=green"

    nginx:
      image: nginx:stable-alpine
      container_name: nginx_gateway
      ports:
        - "${NGINX_HOST_PORT}:80"
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/templates/nginx.conf.template:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - ACTIVE_POOL
      - BLUE_HOST_PORT
      - GREEN_HOST_PORT
    
    command: /bin/sh -c "envsubst '$$ACTIVE_POOL $$BLUE_HOST_PORT $$GREEN_HOST_PORT' < /etc/nginx/templates/nginx.conf.template > /etc/nginx/conf.d/nginx.conf && nginx -g 'daemon off;'"
    depends_on:
      # Nginx needs both apps to be up to start routing
      - app_blue
      - app_green
    restart: unless-stopped
