version: "3.8"

services:
  # --- Node.js Application Services ---
  app_blue:
    image: ${BLUE_IMAGE}
    container_name: app_blue
    environment:
      - APP_POOL=blue
      - RELEASE_ID=${RELEASE_ID_BLUE}
      - PORT=${PORT}
    ports:
      - "${BLUE_HOST_PORT}:${PORT}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/healthz"]
      interval: 5s
      timeout: 3s
      retries: 3
    restart: unless-stopped
    labels:
      - "com.cool-keeds.pool=blue"

  app_green:
    image: ${GREEN_IMAGE}
    container_name: app_green
    environment:
      - APP_POOL=green
      - RELEASE_ID=${RELEASE_ID_GREEN}
      - PORT=${PORT}
    ports:
      - "${GREEN_HOST_PORT}:${PORT}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/healthz"]
      interval: 5s
      timeout: 3s
      retries: 3
    restart: unless-stopped
    labels:
      - "com.cool-keeds.pool=green"

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_gateway
    ports:
      # Public entrypoint (http://localhost:8080)
      - "${NGINX_HOST_PORT}:80"
    volumes:
      # ONLY mount the template config.
      - ./nginx/nginx.conf.template:/etc/nginx/templates/nginx.conf.template:ro
    environment:
      # ONLY pass the variables needed for the Nginx template logic (ACTIVE_POOL and PORT)
      - ACTIVE_POOL
      - PORT    
    command: /bin/sh -c "envsubst '$$ACTIVE_POOL $$PORT' < /etc/nginx/templates/nginx.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - app_blue
      - app_green
    restart: unless-stopped
